USE blis_revamp;

UPDATE lab_config SET name='Bamenda Regional Hospital Lab', location='Bamenda, Cameroon', admin_user_id=115, id_mode=2 WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab', location='Bamenda, Cameroon', admin_user_id=115, id_mode=2 WHERE lab_config_id=128;
UPDATE user SET actualname='', phone='', email='', level=13, lang_id='default' WHERE user_id=337;
UPDATE user SET actualname='', phone='', email='', level=0, lang_id='default' WHERE user_id=337;
UPDATE lab_config SET p_addl=1 WHERE lab_config_id=128;
UPDATE lab_config SET dformat='m-d-Y' WHERE lab_config_id=128;
UPDATE lab_config SET dnum_reset=1 WHERE lab_config_id=128;
UPDATE lab_config SET doctor=1 WHERE lab_config_id=128;
UPDATE lab_config SET p_addl=0 WHERE lab_config_id=128;
UPDATE lab_config SET dformat='m-d-Y' WHERE lab_config_id=128;
UPDATE lab_config SET dnum_reset=1 WHERE lab_config_id=128;
UPDATE lab_config SET doctor=1 WHERE lab_config_id=128;
UPDATE user SET email='', phone='', actualname='Bamenda Admins', lang_id='default' WHERE user_id=115;
UPDATE user SET email='', phone='', actualname='Bamenda Admin', lang_id='default' WHERE user_id=115;
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '0:1,1:10,10:14,14:45,45:+', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '0:1,1:10,10:14,14:45,45:+', ':,' );
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
UPDATE lab_config SET name='Bamenda Regional Hospital Lab' WHERE lab_config_id=128;
UPDATE lab_config SET location='Bamenda, Cameroon' WHERE lab_config_id=128;
2012-05-24 17:24:42	DELETE FROM lab_config_access WHERE lab_config_id=128
2012-05-24 17:24:42	DELETE FROM user WHERE lab_config_id=128
2012-05-24 17:24:42	DELETE FROM report_disease WHERE lab_config_id=128
2012-05-24 17:24:42	DELETE FROM lab_config WHERE lab_config_id=128
2012-05-24 17:30:24	DELETE FROM lab_config_access WHERE lab_config_id=128
2012-05-24 17:30:24	DELETE FROM user WHERE lab_config_id=128
2012-05-24 17:30:24	DELETE FROM report_disease WHERE lab_config_id=128
2012-05-24 17:30:24	DELETE FROM lab_config WHERE lab_config_id=128
