USE blis_revamp;

INSERT INTO TEST_MAPPING VALUES (123,'ASLO','128:64;129:92;131:64');
INSERT INTO TEST_MAPPING VALUES (123,'abc','undefined;undefined;undefined');
INSERT INTO TEST_MAPPING VALUES (123,'abc','undefined;undefined;undefined');
INSERT INTO TEST_MAPPING VALUES (123,'blah','undefined;undefined;undefined');
INSERT INTO TEST_MAPPING VALUES (123,'blah','128:107;129:90;131:142');
INSERT INTO specimen_mapping VALUES (123,'Serum','128:7;129:7;131:7');
INSERT INTO TEST_MAPPING VALUES (123,'Lol','128:107;129:90;131:142', 3);
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id) VALUES (123,'Lol','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id) VALUES (123,'wololo','128:107;129:90;131:142');
INSERT INTO specimen_mapping (user_id, specimen_name, lab_id_specimen_id) VALUES (123,'Lol','');
INSERT INTO specimen_mapping (user_id, specimen_name, lab_id_specimen_id) VALUES (123,'Lol2','');
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id) VALUES (123,'ASLO','128:64;129:92;131:64');
INSERT INTO specimen_mapping (user_id, specimen_name, lab_id_specimen_id) VALUES (123,'Serum','128:7;129:7;131:7');
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 0, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id= AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 0, '', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '1:10', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '1:10', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '1:10', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '1:10', ':,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '0:1,1:10,10:14,14:45', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '0:1,1:10,10:14,14:45', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '0:1,1:10,10:14,14:45', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '0:1,1:10,10:14,14:45', ':,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '0:1,1:10,10:14,14:40', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '0:1,1:10,10:14,14:40', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '0:1,1:10,10:14,14:40', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '0:1,1:10,10:14,14:40', ':,' );
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id) VALUES (123,'Toxoplasma','128:67;129:67;131:89');
UPDATE test_mapping SET test_category_id=1 WHERE test_id=2 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('Toxoplasma', 'NEGATIVE - < 10 IU/ml_POSITIVE - 10 IU/ml_POSITIVE - 20 IU/ml_POSITIVE - 40 IU/ml_POSITIVE - 50 IU/ml_POSITIVE - 80 IU/ml', 2, 123, '< 10 IU/ml');
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '0:1,1:10,10:14,14:45,45:+', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '0:1,1:10,10:14,14:45,45:+', ':,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=3 AND measure_id=7;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 3, 7, 1, 1, '0:1,1:10,10:14,14:45,45:+', '0:1,1:4,4:14,14:45,45:+,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '0:1,1:10,10:14,14:45,45:+', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '0:1,1:10,10:14,14:45,45:+', ':,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=3 AND measure_id=7;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 3, 7, 1, 1, '0:1,1:10,10:14,14:45,45:+', '0:100,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=0 AND measure_id=0;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 0, 0, 1, 1, '0:1,1:10,10:14,14:45,45:+', '' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=1;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 1, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'Positive_Negative:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=2;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 2, 1, 1, '0:1,1:10,10:14,14:45,45:+', 'P1_P2:,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=1 AND measure_id=5;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 1, 5, 1, 1, '0:1,1:10,10:14,14:45,45:+', ':,' );
DELETE FROM infection_report_settings WHERE user_id=123 AND test_id=3 AND measure_id=7;
INSERT INTO infection_report_settings( user_id, test_id, measure_id, group_by_gender, group_by_age, age_groups, measure_groups ) VALUES ( 123, 3, 7, 1, 1, '0:1,1:10,10:14,14:45,45:+', '0:1000,' );
INSERT INTO specimen_mapping (user_id, specimen_name, lab_id_specimen_id, specimen_id) VALUES (123,'Urine','128:11;129:11;131:11',1);
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id, test_id) VALUES (123,'AST/SGOT','128:18;129:18;131:18',1);
INSERT INTO TEST_CATEGORY_MAPPING (user_id, test_category_name, lab_id_test_category_id, test_category_id) VALUES (123,'Serology','128:1;129:1;131:1',1);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('AST/SGOT', ':', 1, 123, 'ml', 1);
INSERT INTO measure_mapping (user_id, measure_name, lab_id_measure_id, measure_id) VALUES (123,'a','128:238;129:117;131:64',1);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='AST/SGOT', range=':', unit='ml' WHERE measure_id=1;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '0', '', '0', '100', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='AST/SGOT', range=':', unit='ml' WHERE measure_id=1;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, '', 2);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '2', '', '0', '100', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='AST/SGOT', range=':', unit='ml' WHERE measure_id=1;
DELETE FROM reference_range_global WHERE measure_id=2;
UPDATE global_measures SET name='Test', range=':', unit='' WHERE measure_id=2;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '2', 'B', '0', '100', 123);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (2, '0', '0', 'B', '0', '100', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='AST/SGOT', range=':', unit='ml' WHERE measure_id=1;
DELETE FROM reference_range_global WHERE measure_id=2;
UPDATE global_measures SET name='Test', range=':', unit='mls' WHERE measure_id=2;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '2', 'B', '0', '100', 123);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (2, '0', '5', 'B', '1', '200', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='AST/SGOT', range=':', unit='ml' WHERE measure_id=1;
DELETE FROM reference_range_global WHERE measure_id=2;
UPDATE global_measures SET name='Test', range=':', unit='mls' WHERE measure_id=2;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test2', ':', 1, 123, 'sml', 3);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '2', 'B', '0', '100', 123);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (2, '0', '5', 'B', '1', '200', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='AST/SGOT', range=':', unit='ml' WHERE measure_id=1;
DELETE FROM reference_range_global WHERE measure_id=2;
UPDATE global_measures SET name='Test', range=':', unit='mls' WHERE measure_id=2;
DELETE FROM reference_range_global WHERE measure_id=3;
UPDATE global_measures SET name='Test2', range=':', unit='sml' WHERE measure_id=3;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '2', 'B', '0', '100', 123);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (2, '0', '5', 'B', '1', '200', 123);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (3, '0', '0', 'B', '1', '200', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 1);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 2);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 3);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 4);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 5);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 6);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 7);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (7, '0', '100', 'B', '1', '2', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test', ':', 1, 123, 'ml', 1);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '100', 'B', '1', '2', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
DELETE FROM reference_range_global WHERE measure_id=1;
UPDATE global_measures SET name='Test', range=':', unit='ml' WHERE measure_id=1;
INSERT INTO global_measures (name, range, test_id, user_id, unit, measure_id ) VALUES ('Test2', ':', 1, 123, 'mls', 2);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (1, '0', '100', 'B', '1', '2', 123);
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (2, '0', '100', 'B', '5', '10', 123);
