USE blis_-1;

INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
INSERT INTO user_rating (user_id, rating) VALUES (123, 6);
