USE blis_revamp;

INSERT INTO TEST_MAPPING VALUES (123,'Test','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'Test','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'Test','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'Test','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'Test','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'blah','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'blah','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'blah2','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'blah3','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'blah','128:107;129:90;131:142');
INSERT INTO TEST_MAPPING VALUES (123,'a','');
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id) VALUES (123,'ASLO','128:64;129:92;131:64');
INSERT INTO specimen_mapping (user_id, specimen_name, lab_id_specimen_id) VALUES (123,'Serum','128:7;129:7;131:7');
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('A1', 'Positive_Negative', 1, 123, '');
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('A3', 'P1_P2', 1, 123, '');
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('A3', 'P1_P2', 1, 123, '');
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE measure SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE measure SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('A4', ':', 1, 123, '');
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('A5', ':', 1, 123, '');
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A5', range=':', unit='' WHERE measure_id=5;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A5', range=':', unit='' WHERE measure_id=5;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A5', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '0', '', '22', '25', 123);
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A5', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '22', '52', 123);
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A1', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '16', '100', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A1', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '16', '100', 123);
UPDATE test_mapping SET test_category_id=6 WHERE test_id=1 ;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A1', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '16', '100', 123);
UPDATE test_mapping SET test_category_id=1 WHERE test_id=1 ;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A1', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '16', '100', 123);
UPDATE test_mapping SET test_category_id=6 WHERE test_id=1 ;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A1', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '16', '100', 123);
UPDATE test_mapping SET test_category_id=5 WHERE test_id=1 ;
UPDATE global_measures SET name='A2', range='Positive_Negative', unit='' WHERE measure_id=1;
UPDATE global_measures SET name='A3', range='P1_P2', unit='' WHERE measure_id=2;
UPDATE global_measures SET name='A4', range='22/25', unit='' WHERE measure_id=4;
DELETE FROM reference_range_global WHERE measure_id=5;
UPDATE global_measures SET name='A1', range=':', unit='' WHERE measure_id=5;
INSERT INTO reference_range_global (measure_id, age_min, age_max, sex, range_lower, range_upper, user_id) VALUES (5, '0', '100', 'B', '16', '100', 123);
INSERT INTO measure_mapping (user_id, measure_name, lab_id_measure_id) VALUES (123,'AST/SGOT','128:16;129:16;131:16');
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id) VALUES (123,'AST/SGOT','128:18;129:18;131:18');
UPDATE test_mapping SET test_category_id=8 WHERE test_id=3 ;
INSERT INTO global_measures (name, range, test_id, user_id, unit ) VALUES ('AST/SGOT', ':', 3, 123, 'U/L');
INSERT INTO measure_mapping (user_id, measure_name, lab_id_measure_id, measure_id) VALUES (123,'a1','128:238;129:117;131:64',3);
INSERT INTO measure_mapping (user_id, measure_name, lab_id_measure_id, measure_id) VALUES (123,'a','128:238;129:117;131:64',3);
INSERT INTO TEST_CATEGORY_MAPPING (user_id, test_category_name, lab_id_test_category_id, test_category_id) VALUES (123,'s','128:1;129:1;131:1',13);
INSERT INTO TEST_MAPPING (user_id, test_name, lab_id_test_id, test_id) VALUES (123,'s','128:107;129:90;131:142',4);
INSERT INTO specimen_mapping (user_id, specimen_name, lab_id_specimen_id, specimen_id) VALUES (123,'s','128:10;129:10;131:25',2);
