USE blis_151;

INSERT INTO lab_config_specimen_type(lab_config_id, specimen_type_id) VALUES (151, 11);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 85);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 8);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 18);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 25);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 22);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 103);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 9);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 90);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 49);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 29);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 37);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 24);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 30);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 23);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 31);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 59);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 53);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 71);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 102);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 28);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 108);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 56);
INSERT INTO lab_config_test_type(lab_config_id, test_type_id) VALUES (151, 96);
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('85', 'Worksheet - AFB', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('8', 'Worksheet - ALT/SGPT', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('18', 'Worksheet - AST/SGOT', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('25', 'Worksheet - Cl- ', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('22', 'Worksheet - Creatinine', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('103', 'Worksheet - Direct Bilirubin', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('90', 'Worksheet - Hb', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('49', 'Worksheet - Hb Electropherosis', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('24', 'Worksheet - K+', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('23', 'Worksheet - Na+', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('71', 'Worksheet - Stool Analysis', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('102', 'Worksheet - Total Bilirubin', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
INSERT INTO report_config (test_type_id, header, footer, margins, p_fields, s_fields, t_fields, p_custom_fields, s_custom_fields ) VALUES ('108', 'Worksheet - Urea', '', '5,0,5,0', '0,1,0,1,1,0,0', '0,0,1,1,0,0', '1,0,1,0,0,0,0,1', '', '' );
DELETE FROM report_disease WHERE lab_config_id=151 AND test_type_id=0 AND measure_id=0;
INSERT INTO user_rating (user_id, rating) VALUES (340, 6);
INSERT INTO user_rating (user_id, rating) VALUES (340, 6);
INSERT INTO user_rating (user_id, rating) VALUES (340, 6);
