version: '3'

services:
  app:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    environment:
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PASS: 'blis123'
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    restart: unless-stopped
    volumes:
      - blis-data:/var/lib/mysql
      - type: bind
        source: ./docker/database
        target: /docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: blis123

volumes:
  blis-data: