ALTER TABLE `bills` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `bills` ADD COLUMN `patient_id` int(11) unsigned NOT NULL;
ALTER TABLE `bills` ADD COLUMN `paid_in_full` bit(1) NOT NULL DEFAULT b'0';
ALTER TABLE `bills` ADD PRIMARY KEY(`id`);
ALTER TABLE `bills_test_association` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `bills_test_association` ADD COLUMN `bill_id` int(11) unsigned NOT NULL;
ALTER TABLE `bills_test_association` ADD COLUMN `test_id` int(11) unsigned NOT NULL;
ALTER TABLE `bills_test_association` ADD COLUMN `discount_type` int(4) unsigned NOT NULL DEFAULT 1000;
ALTER TABLE `bills_test_association` ADD COLUMN `discount_amount` decimal(10,2) unsigned NOT NULL DEFAULT 0.00;
ALTER TABLE `bills_test_association` ADD PRIMARY KEY(`id`);
ALTER TABLE `blis_backups` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `blis_backups` ADD COLUMN `lab_config_id` int(10) unsigned NOT NULL;
ALTER TABLE `blis_backups` ADD COLUMN `filename` varchar(100) NOT NULL;
ALTER TABLE `blis_backups` ADD COLUMN `location` varchar(100) NOT NULL;
ALTER TABLE `blis_backups` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `blis_backups` ADD PRIMARY KEY(`id`);
ALTER TABLE `blis_migrations` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `blis_migrations` ADD COLUMN `name` varchar(100) NOT NULL;
ALTER TABLE `blis_migrations` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `blis_migrations` ADD PRIMARY KEY(`id`);
ALTER TABLE `comment` ADD COLUMN `id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `comment` ADD COLUMN `username` varchar(45) NOT NULL;
ALTER TABLE `comment` ADD COLUMN `page` varchar(45) NOT NULL;
ALTER TABLE `comment` ADD COLUMN `comment` varchar(150) NOT NULL;
ALTER TABLE `comment` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `comment` ADD PRIMARY KEY(`id`);
ALTER TABLE `currency_conversion` ADD COLUMN `currencya` varchar(200) NOT NULL;
ALTER TABLE `currency_conversion` ADD COLUMN `currencyb` varchar(200) NOT NULL;
ALTER TABLE `currency_conversion` ADD COLUMN `exchangerate` float(5,2) DEFAULT NULL;
ALTER TABLE `currency_conversion` ADD COLUMN `updatedts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `currency_conversion` ADD COLUMN `flag1` int(11) DEFAULT NULL;
ALTER TABLE `currency_conversion` ADD COLUMN `flag2` int(11) DEFAULT NULL;
ALTER TABLE `currency_conversion` ADD COLUMN `setting1` varchar(200) DEFAULT NULL;
ALTER TABLE `currency_conversion` ADD COLUMN `setting2` varchar(200) DEFAULT NULL;
ALTER TABLE `currency_conversion` ADD PRIMARY KEY(`currencya`, `currencyb`);
ALTER TABLE `custom_field_type` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `custom_field_type` ADD COLUMN `field_type` varchar(100) DEFAULT NULL;
ALTER TABLE `custom_field_type` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `custom_field_type` ADD PRIMARY KEY(`id`);
ALTER TABLE `delay_measures` ADD COLUMN `User_Id` varchar(50) NOT NULL;
ALTER TABLE `delay_measures` ADD COLUMN `IP_Address` varchar(16) NOT NULL;
ALTER TABLE `delay_measures` ADD COLUMN `Latency` int(11) NOT NULL;
ALTER TABLE `delay_measures` ADD COLUMN `Recorded_At` datetime NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `delay_measures` ADD COLUMN `Page_Name` varchar(45) DEFAULT NULL;
ALTER TABLE `delay_measures` ADD COLUMN `Request_URI` varchar(100) DEFAULT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `dhims2_api_config` ADD COLUMN `username` varchar(50) NOT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `password` varchar(50) NOT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `orgunit` varchar(200) NOT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `dataset` varchar(200) NOT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `dataelement` text NOT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `categorycombo` varchar(100) DEFAULT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `gender` varchar(5) DEFAULT NULL;
ALTER TABLE `dhims2_api_config` ADD COLUMN `period` varchar(10) DEFAULT NULL;
ALTER TABLE `dhims2_api_config` ADD PRIMARY KEY(`id`);
ALTER TABLE `field_order` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `field_order` ADD COLUMN `lab_config_id` int(11) unsigned DEFAULT NULL;
ALTER TABLE `field_order` ADD COLUMN `form_id` int(11) DEFAULT NULL;
ALTER TABLE `field_order` ADD COLUMN `field_order` varchar(2000) DEFAULT NULL;
ALTER TABLE `field_order` ADD PRIMARY KEY(`id`);
ALTER TABLE `inv_reagent` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `inv_reagent` ADD COLUMN `name` varchar(100) NOT NULL;
ALTER TABLE `inv_reagent` ADD COLUMN `unit` varchar(45) NOT NULL DEFAULT 'units';
ALTER TABLE `inv_reagent` ADD COLUMN `remarks` varchar(245) DEFAULT NULL;
ALTER TABLE `inv_reagent` ADD COLUMN `created_by` varchar(10) NOT NULL;
ALTER TABLE `inv_reagent` ADD COLUMN `assocation` varchar(10) DEFAULT NULL;
ALTER TABLE `inv_reagent` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `inv_reagent` ADD PRIMARY KEY(`id`);
ALTER TABLE `inv_supply` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `inv_supply` ADD COLUMN `reagent_id` int(11) NOT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `lot` varchar(100) NOT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `expiry_date` date DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `manufacturer` varchar(100) DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `supplier` varchar(100) DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `quantity_ordered` int(11) NOT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `quantity_supplied` int(11) NOT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `cost_per_unit` decimal(10,0) DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `user_id` int(11) NOT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `date_of_order` date DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `date_of_supply` date DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `date_of_reception` date DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `remarks` varchar(250) DEFAULT NULL;
ALTER TABLE `inv_supply` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `inv_supply` ADD PRIMARY KEY(`id`);
ALTER TABLE `inv_usage` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `inv_usage` ADD COLUMN `reagent_id` int(11) NOT NULL;
ALTER TABLE `inv_usage` ADD COLUMN `lot` varchar(100) NOT NULL;
ALTER TABLE `inv_usage` ADD COLUMN `quantity_used` int(11) NOT NULL;
ALTER TABLE `inv_usage` ADD COLUMN `date_of_use` date NOT NULL;
ALTER TABLE `inv_usage` ADD COLUMN `user_id` int(11) NOT NULL;
ALTER TABLE `inv_usage` ADD COLUMN `remarks` varchar(250) DEFAULT NULL;
ALTER TABLE `inv_usage` ADD COLUMN `ts` timestamp DEFAULT NULL;
ALTER TABLE `inv_usage` ADD PRIMARY KEY(`id`);
ALTER TABLE `lab_config` ADD COLUMN `lab_config_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `lab_config` ADD COLUMN `name` char(45) NOT NULL;
ALTER TABLE `lab_config` ADD COLUMN `location` char(45) NOT NULL;
ALTER TABLE `lab_config` ADD COLUMN `admin_user_id` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config` ADD COLUMN `db_name` char(45) NOT NULL;
ALTER TABLE `lab_config` ADD COLUMN `id_mode` int(10) unsigned NOT NULL DEFAULT 2;
ALTER TABLE `lab_config` ADD COLUMN `p_addl` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config` ADD COLUMN `s_addl` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config` ADD COLUMN `daily_num` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `pid` int(10) unsigned NOT NULL DEFAULT 2;
ALTER TABLE `lab_config` ADD COLUMN `pname` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `sex` int(10) unsigned NOT NULL DEFAULT 2;
ALTER TABLE `lab_config` ADD COLUMN `age` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `dob` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `sid` int(10) unsigned NOT NULL DEFAULT 2;
ALTER TABLE `lab_config` ADD COLUMN `refout` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `rdate` int(10) unsigned NOT NULL DEFAULT 2;
ALTER TABLE `lab_config` ADD COLUMN `comm` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `dformat` varchar(45) NOT NULL DEFAULT 'd-m-Y';
ALTER TABLE `lab_config` ADD COLUMN `dnum_reset` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `doctor` int(10) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `lab_config` ADD COLUMN `ageLimit` int(11) DEFAULT NULL;
ALTER TABLE `lab_config` ADD PRIMARY KEY(`lab_config_id`);
ALTER TABLE `lab_config_access` ADD COLUMN `user_id` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config_access` ADD COLUMN `lab_config_id` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config_access` ADD PRIMARY KEY(`user_id`, `lab_config_id`);
ALTER TABLE `lab_config_settings` ADD COLUMN `id` int(11) NOT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `flag1` int(11) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `flag2` int(11) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `flag3` int(11) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `flag4` int(11) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `setting1` varchar(200) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `setting2` varchar(200) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `setting3` varchar(200) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `setting4` varchar(200) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `misc` varchar(500) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `remarks` varchar(500) DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD COLUMN `ts` timestamp DEFAULT NULL;
ALTER TABLE `lab_config_settings` ADD PRIMARY KEY(`id`);
ALTER TABLE `lab_config_specimen_type` ADD COLUMN `lab_config_id` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config_specimen_type` ADD COLUMN `specimen_type_id` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config_test_type` ADD COLUMN `lab_config_id` int(10) unsigned NOT NULL;
ALTER TABLE `lab_config_test_type` ADD COLUMN `test_type_id` int(10) unsigned NOT NULL;
ALTER TABLE `labtitle_custom_field` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `labtitle_custom_field` ADD COLUMN `field_name` varchar(45) NOT NULL;
ALTER TABLE `labtitle_custom_field` ADD COLUMN `field_options` varchar(200) NOT NULL;
ALTER TABLE `labtitle_custom_field` ADD COLUMN `field_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `labtitle_custom_field` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `labtitle_custom_field` ADD PRIMARY KEY(`id`);
ALTER TABLE `measure` ADD COLUMN `measure_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `measure` ADD COLUMN `name` varchar(45) NOT NULL;
ALTER TABLE `measure` ADD COLUMN `unit_id` int(10) unsigned DEFAULT NULL;
ALTER TABLE `measure` ADD COLUMN `range` varchar(500) DEFAULT NULL;
ALTER TABLE `measure` ADD COLUMN `description` varchar(500) DEFAULT NULL;
ALTER TABLE `measure` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `measure` ADD COLUMN `unit` varchar(30) DEFAULT NULL;
ALTER TABLE `measure` ADD PRIMARY KEY(`measure_id`);
ALTER TABLE `misc` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `misc` ADD COLUMN `r_id` int(11) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `vr_id` varchar(45) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `i1` int(11) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `i2` int(11) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `i3` int(11) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `i4` int(11) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `i5` int(11) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `v1` varchar(500) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `v2` varchar(500) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `v3` varchar(500) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `v4` varchar(500) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `v5` varchar(500) NOT NULL;
ALTER TABLE `misc` ADD COLUMN `dt1` datetime DEFAULT NULL;
ALTER TABLE `misc` ADD COLUMN `dt2` datetime DEFAULT NULL;
ALTER TABLE `misc` ADD COLUMN `dt3` datetime DEFAULT NULL;
ALTER TABLE `misc` ADD COLUMN `d1` date DEFAULT NULL;
ALTER TABLE `misc` ADD COLUMN `d2` date DEFAULT NULL;
ALTER TABLE `misc` ADD COLUMN `d3` date DEFAULT NULL;
ALTER TABLE `misc` ADD COLUMN `ts` timestamp DEFAULT NULL;
ALTER TABLE `misc` ADD PRIMARY KEY(`id`);
ALTER TABLE `numeric_interpretation` ADD COLUMN `range_u` int(10) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `range_l` int(10) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `age_u` int(10) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `age_l` int(10) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `gender` varchar(40) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `description` varchar(40) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `measure_id` int(10) DEFAULT NULL;
ALTER TABLE `numeric_interpretation` ADD COLUMN `id` int(10) NOT NULL auto_increment;
ALTER TABLE `numeric_interpretation` ADD PRIMARY KEY(`id`);
ALTER TABLE `patient` ADD COLUMN `patient_id` int(11) unsigned NOT NULL;
ALTER TABLE `patient` ADD COLUMN `addl_id` varchar(40) DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `name` varchar(45) DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `sex` char(1) NOT NULL;
ALTER TABLE `patient` ADD COLUMN `age` decimal(10,0) DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `dob` date DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `created_by` int(11) unsigned DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `patient` ADD COLUMN `partial_dob` varchar(45) DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `surr_id` varchar(45) DEFAULT NULL;
ALTER TABLE `patient` ADD COLUMN `hash_value` varchar(100) DEFAULT NULL;
ALTER TABLE `patient` ADD PRIMARY KEY(`patient_id`);
ALTER TABLE `patient_custom_data` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `patient_custom_data` ADD COLUMN `field_id` int(11) unsigned NOT NULL;
ALTER TABLE `patient_custom_data` ADD COLUMN `patient_id` int(11) unsigned NOT NULL;
ALTER TABLE `patient_custom_data` ADD COLUMN `field_value` varchar(45) NOT NULL;
ALTER TABLE `patient_custom_data` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `patient_custom_data` ADD PRIMARY KEY(`id`);
ALTER TABLE `patient_custom_field` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `patient_custom_field` ADD COLUMN `field_name` varchar(45) NOT NULL;
ALTER TABLE `patient_custom_field` ADD COLUMN `field_options` varchar(16000) DEFAULT NULL;
ALTER TABLE `patient_custom_field` ADD COLUMN `field_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `patient_custom_field` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `patient_custom_field` ADD PRIMARY KEY(`id`);
ALTER TABLE `patient_daily` ADD COLUMN `datestring` varchar(45) NOT NULL;
ALTER TABLE `patient_daily` ADD COLUMN `count` int(10) unsigned NOT NULL;
ALTER TABLE `patient_report_fields_order` ADD COLUMN `id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `patient_report_fields_order` ADD COLUMN `p_fields` varchar(500) NOT NULL;
ALTER TABLE `patient_report_fields_order` ADD COLUMN `o_fields` varchar(500) NOT NULL;
ALTER TABLE `patient_report_fields_order` ADD PRIMARY KEY(`id`);
ALTER TABLE `payments` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `payments` ADD COLUMN `amount` decimal(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE `payments` ADD COLUMN `bill_id` int(11) unsigned NOT NULL;
ALTER TABLE `payments` ADD PRIMARY KEY(`id`);
ALTER TABLE `reference_range` ADD COLUMN `id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `reference_range` ADD COLUMN `measure_id` int(10) unsigned NOT NULL;
ALTER TABLE `reference_range` ADD COLUMN `age_min` varchar(45) DEFAULT NULL;
ALTER TABLE `reference_range` ADD COLUMN `age_max` varchar(45) DEFAULT NULL;
ALTER TABLE `reference_range` ADD COLUMN `sex` varchar(10) DEFAULT NULL;
ALTER TABLE `reference_range` ADD COLUMN `range_lower` varchar(45) NOT NULL;
ALTER TABLE `reference_range` ADD COLUMN `range_upper` varchar(45) NOT NULL;
ALTER TABLE `reference_range` ADD PRIMARY KEY(`id`);
ALTER TABLE `removal_record` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `removal_record` ADD COLUMN `r_id` int(11) NOT NULL;
ALTER TABLE `removal_record` ADD COLUMN `vr_id` varchar(45) NOT NULL;
ALTER TABLE `removal_record` ADD COLUMN `type` int(11) DEFAULT NULL;
ALTER TABLE `removal_record` ADD COLUMN `user_id` int(11) DEFAULT NULL;
ALTER TABLE `removal_record` ADD COLUMN `remarks` varchar(500) DEFAULT NULL;
ALTER TABLE `removal_record` ADD COLUMN `status` int(11) NOT NULL DEFAULT 1;
ALTER TABLE `removal_record` ADD COLUMN `ts` timestamp DEFAULT NULL;
ALTER TABLE `removal_record` ADD COLUMN `category` varchar(20) DEFAULT NULL;
ALTER TABLE `removal_record` ADD PRIMARY KEY(`id`);
ALTER TABLE `report_config` ADD COLUMN `report_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `report_config` ADD COLUMN `header` varchar(500) NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `footer` varchar(500) NOT NULL DEFAULT '-End-';
ALTER TABLE `report_config` ADD COLUMN `margins` varchar(45) NOT NULL DEFAULT '2,0,10,0';
ALTER TABLE `report_config` ADD COLUMN `p_fields` varchar(45) NOT NULL DEFAULT '1,1,1,1,1,1,1';
ALTER TABLE `report_config` ADD COLUMN `s_fields` varchar(45) NOT NULL DEFAULT '1,1,1,1,1,1';
ALTER TABLE `report_config` ADD COLUMN `t_fields` varchar(45) NOT NULL DEFAULT '1,0,1,1,1,0,1,1';
ALTER TABLE `report_config` ADD COLUMN `p_custom_fields` varchar(45) NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `s_custom_fields` varchar(45) NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `test_type_id` varchar(45) NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `title` varchar(500) NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `landscape` int(10) unsigned NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `row_items` int(1) unsigned NOT NULL DEFAULT 3;
ALTER TABLE `report_config` ADD COLUMN `show_border` int(1) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `report_config` ADD COLUMN `show_result_border` int(1) unsigned NOT NULL DEFAULT 1;
ALTER TABLE `report_config` ADD COLUMN `result_border_horizontal` int(1) unsigned NOT NULL;
ALTER TABLE `report_config` ADD COLUMN `result_border_vertical` int(1) unsigned NOT NULL;
ALTER TABLE `report_config` ADD PRIMARY KEY(`report_id`);
ALTER TABLE `report_disease` ADD COLUMN `id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `report_disease` ADD COLUMN `group_by_age` int(10) unsigned NOT NULL;
ALTER TABLE `report_disease` ADD COLUMN `group_by_gender` int(10) unsigned NOT NULL;
ALTER TABLE `report_disease` ADD COLUMN `age_groups` varchar(500) DEFAULT NULL;
ALTER TABLE `report_disease` ADD COLUMN `measure_groups` varchar(500) DEFAULT NULL;
ALTER TABLE `report_disease` ADD COLUMN `measure_id` int(10) unsigned NOT NULL;
ALTER TABLE `report_disease` ADD COLUMN `lab_config_id` int(10) unsigned NOT NULL;
ALTER TABLE `report_disease` ADD COLUMN `test_type_id` int(10) unsigned NOT NULL;
ALTER TABLE `report_disease` ADD PRIMARY KEY(`id`);
ALTER TABLE `sites` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `sites` ADD COLUMN `name` varchar(255) DEFAULT NULL;
ALTER TABLE `sites` ADD COLUMN `lab_id` int(11) DEFAULT NULL;
ALTER TABLE `sites` ADD COLUMN `Region` varchar(40) DEFAULT NULL;
ALTER TABLE `sites` ADD COLUMN `District` varchar(40) DEFAULT NULL;
ALTER TABLE `sites` ADD PRIMARY KEY(`id`);
ALTER TABLE `specimen` ADD COLUMN `specimen_id` int(10) unsigned NOT NULL;
ALTER TABLE `specimen` ADD COLUMN `patient_id` int(11) unsigned NOT NULL;
ALTER TABLE `specimen` ADD COLUMN `specimen_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `specimen` ADD COLUMN `user_id` int(11) unsigned DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `specimen` ADD COLUMN `status_code_id` int(11) unsigned DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `referred_to` int(11) unsigned DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `comments` text DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `aux_id` varchar(45) DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `date_collected` date NOT NULL DEFAULT 0000-00-00;
ALTER TABLE `specimen` ADD COLUMN `date_recvd` date DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `session_num` varchar(45) DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `time_collected` varchar(45) DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `report_to` int(10) unsigned DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `doctor` varchar(45) DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `date_reported` datetime DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `referred_to_name` varchar(70) DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `daily_num` varchar(45) NOT NULL;
ALTER TABLE `specimen` ADD COLUMN `referred_from_name` varchar(20) DEFAULT NULL;
ALTER TABLE `specimen` ADD COLUMN `site_id` int(11) DEFAULT NULL;
ALTER TABLE `specimen` ADD PRIMARY KEY(`specimen_id`);
ALTER TABLE `specimen_custom_data` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `specimen_custom_data` ADD COLUMN `field_id` int(11) unsigned NOT NULL;
ALTER TABLE `specimen_custom_data` ADD COLUMN `specimen_id` int(10) unsigned NOT NULL;
ALTER TABLE `specimen_custom_data` ADD COLUMN `field_value` varchar(45) NOT NULL;
ALTER TABLE `specimen_custom_data` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `specimen_custom_data` ADD PRIMARY KEY(`id`);
ALTER TABLE `specimen_custom_field` ADD COLUMN `id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `specimen_custom_field` ADD COLUMN `field_name` varchar(45) NOT NULL;
ALTER TABLE `specimen_custom_field` ADD COLUMN `field_options` varchar(16000) DEFAULT NULL;
ALTER TABLE `specimen_custom_field` ADD COLUMN `field_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `specimen_custom_field` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `specimen_custom_field` ADD PRIMARY KEY(`id`);
ALTER TABLE `specimen_session` ADD COLUMN `session_num` varchar(45) NOT NULL;
ALTER TABLE `specimen_session` ADD COLUMN `count` int(10) unsigned NOT NULL;
ALTER TABLE `specimen_session` ADD PRIMARY KEY(`session_num`);
ALTER TABLE `specimen_test` ADD COLUMN `test_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `specimen_test` ADD COLUMN `specimen_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `specimen_test` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `specimen_type` ADD COLUMN `specimen_type_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `specimen_type` ADD COLUMN `name` varchar(45) NOT NULL;
ALTER TABLE `specimen_type` ADD COLUMN `description` varchar(100) DEFAULT NULL;
ALTER TABLE `specimen_type` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `specimen_type` ADD COLUMN `disabled` int(10) unsigned NOT NULL;
ALTER TABLE `specimen_type` ADD PRIMARY KEY(`specimen_type_id`);
ALTER TABLE `stock_content` ADD COLUMN `name` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_content` ADD COLUMN `current_quantity` int(11) DEFAULT NULL;
ALTER TABLE `stock_content` ADD COLUMN `date_of_use` date NOT NULL;
ALTER TABLE `stock_content` ADD COLUMN `receiver` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_content` ADD COLUMN `remarks` text DEFAULT NULL;
ALTER TABLE `stock_content` ADD COLUMN `lot_number` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_content` ADD COLUMN `new_balance` int(11) DEFAULT NULL;
ALTER TABLE `stock_content` ADD COLUMN `user_name` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `name` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `lot_number` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `expiry_date` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `manufacturer` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `quantity_ordered` int(11) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `supplier` varchar(40) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `date_of_reception` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `stock_details` ADD COLUMN `current_quantity` int(11) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `date_of_supply` timestamp NOT NULL DEFAULT 0000-00-00 00:00:00;
ALTER TABLE `stock_details` ADD COLUMN `quantity_supplied` int(11) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `unit` varchar(10) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `entry_id` int(11) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `cost_per_unit` decimal(10,0) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `quantity_used` int(10) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `used` varchar(1000) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `user` varchar(1000) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `receiver` varchar(1000) DEFAULT NULL;
ALTER TABLE `stock_details` ADD COLUMN `remarks` varchar(1000) DEFAULT NULL;
ALTER TABLE `test` ADD COLUMN `test_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `test` ADD COLUMN `test_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `test` ADD COLUMN `result` varchar(5000) DEFAULT NULL;
ALTER TABLE `test` ADD COLUMN `comments` varchar(200) DEFAULT NULL;
ALTER TABLE `test` ADD COLUMN `user_id` int(11) unsigned DEFAULT NULL;
ALTER TABLE `test` ADD COLUMN `verified_by` int(11) unsigned DEFAULT NULL;
ALTER TABLE `test` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `test` ADD COLUMN `specimen_id` int(11) unsigned DEFAULT NULL;
ALTER TABLE `test` ADD COLUMN `date_verified` datetime DEFAULT NULL;
ALTER TABLE `test` ADD PRIMARY KEY(`test_id`);
ALTER TABLE `test_agg_report_config` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `test_agg_report_config` ADD COLUMN `test_type_id` int(11) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD COLUMN `title` varchar(255) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD COLUMN `landscape` tinyint(1) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD COLUMN `group_by_age` tinyint(1) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD COLUMN `age_unit` int(11) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD COLUMN `age_groups` varchar(255) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD COLUMN `report_type` int(11) DEFAULT NULL;
ALTER TABLE `test_agg_report_config` ADD PRIMARY KEY(`id`);
ALTER TABLE `test_category` ADD COLUMN `test_category_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `test_category` ADD COLUMN `name` varchar(45) NOT NULL;
ALTER TABLE `test_category` ADD COLUMN `description` varchar(100) DEFAULT NULL;
ALTER TABLE `test_category` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `test_category` ADD PRIMARY KEY(`test_category_id`);
ALTER TABLE `test_type` ADD COLUMN `test_type_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `test_type` ADD COLUMN `name` varchar(45) NOT NULL;
ALTER TABLE `test_type` ADD COLUMN `description` varchar(100) DEFAULT NULL;
ALTER TABLE `test_type` ADD COLUMN `test_category_id` int(11) unsigned NOT NULL;
ALTER TABLE `test_type` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `test_type` ADD COLUMN `is_panel` int(10) unsigned DEFAULT NULL;
ALTER TABLE `test_type` ADD COLUMN `disabled` int(10) unsigned NOT NULL;
ALTER TABLE `test_type` ADD COLUMN `clinical_data` longtext DEFAULT NULL;
ALTER TABLE `test_type` ADD COLUMN `hide_patient_name` int(1) DEFAULT NULL;
ALTER TABLE `test_type` ADD COLUMN `prevalence_threshold` int(3) DEFAULT NULL;
ALTER TABLE `test_type` ADD COLUMN `target_tat` int(3) DEFAULT NULL;
ALTER TABLE `test_type` ADD COLUMN `is_reporting_enabled` tinyint(1) DEFAULT NULL;
ALTER TABLE `test_type` ADD PRIMARY KEY(`test_type_id`);
ALTER TABLE `test_type_costs` ADD COLUMN `earliest_date_valid` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `test_type_costs` ADD COLUMN `test_type_id` int(11) NOT NULL;
ALTER TABLE `test_type_costs` ADD COLUMN `amount` decimal(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE `test_type_measure` ADD COLUMN `test_type_id` int(11) unsigned NOT NULL;
ALTER TABLE `test_type_measure` ADD COLUMN `measure_id` int(11) unsigned NOT NULL;
ALTER TABLE `test_type_measure` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `unit` ADD COLUMN `unit_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `unit` ADD COLUMN `unit` varchar(45) NOT NULL;
ALTER TABLE `unit` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `unit` ADD PRIMARY KEY(`unit_id`);
ALTER TABLE `user` ADD COLUMN `user_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `user` ADD COLUMN `username` varchar(45) NOT NULL;
ALTER TABLE `user` ADD COLUMN `password` varchar(45) NOT NULL;
ALTER TABLE `user` ADD COLUMN `actualname` varchar(45) DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `email` varchar(45) DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `created_by` int(11) unsigned DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP;
ALTER TABLE `user` ADD COLUMN `lab_config_id` int(10) unsigned DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `level` int(10) unsigned DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `phone` varchar(45) DEFAULT NULL;
ALTER TABLE `user` ADD COLUMN `lang_id` varchar(45) NOT NULL DEFAULT 'default';
ALTER TABLE `user` ADD PRIMARY KEY(`user_id`);
ALTER TABLE `user_feedback` ADD COLUMN `id` int(11) NOT NULL auto_increment;
ALTER TABLE `user_feedback` ADD COLUMN `user_id` int(11) DEFAULT NULL;
ALTER TABLE `user_feedback` ADD COLUMN `rating` int(3) DEFAULT NULL;
ALTER TABLE `user_feedback` ADD COLUMN `comments` varchar(500) DEFAULT NULL;
ALTER TABLE `user_feedback` ADD COLUMN `ts` timestamp DEFAULT NULL;
ALTER TABLE `user_feedback` ADD PRIMARY KEY(`id`);
ALTER TABLE `user_props` ADD COLUMN `User_Id` varchar(50) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `AppCodeName` varchar(25) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `AppName` varchar(25) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `AppVersion` varchar(25) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `CookieEnabled` tinyint(1) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `Platform` varchar(20) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `UserAgent` varchar(200) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `SystemLanguage` varchar(15) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `UserLanguage` varchar(15) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `Language` varchar(15) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `ScreenAvailHeight` int(11) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `ScreenAvailWidth` int(11) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `ScreenColorDepth` int(11) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `ScreenHeight` int(11) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `ScreenWidth` int(11) NOT NULL;
ALTER TABLE `user_props` ADD COLUMN `Recorded_At` datetime NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `user_rating` ADD COLUMN `user_id` int(10) unsigned NOT NULL;
ALTER TABLE `user_rating` ADD COLUMN `rating` int(10) unsigned NOT NULL;
ALTER TABLE `user_rating` ADD COLUMN `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `user_rating` ADD PRIMARY KEY(`user_id`, `ts`);
ALTER TABLE `worksheet_custom` ADD COLUMN `id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `worksheet_custom` ADD COLUMN `name` varchar(100) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `header` varchar(500) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `footer` varchar(500) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `title` varchar(500) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `p_fields` varchar(100) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `s_fields` varchar(100) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `t_fields` varchar(100) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `p_custom` varchar(100) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `s_custom` varchar(100) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `margins` varchar(50) NOT NULL;
ALTER TABLE `worksheet_custom` ADD COLUMN `id_fields` varchar(45) NOT NULL DEFAULT '0,0,0';
ALTER TABLE `worksheet_custom` ADD COLUMN `landscape` int(10) unsigned NOT NULL;
ALTER TABLE `worksheet_custom` ADD PRIMARY KEY(`id`);
ALTER TABLE `worksheet_custom_test` ADD COLUMN `worksheet_id` int(10) unsigned NOT NULL;
ALTER TABLE `worksheet_custom_test` ADD COLUMN `test_type_id` int(10) unsigned NOT NULL;
ALTER TABLE `worksheet_custom_test` ADD COLUMN `measure_id` int(10) unsigned NOT NULL;
ALTER TABLE `worksheet_custom_test` ADD COLUMN `width` varchar(45) NOT NULL;
ALTER TABLE `worksheet_custom_userfield` ADD COLUMN `worksheet_id` int(10) unsigned NOT NULL;
ALTER TABLE `worksheet_custom_userfield` ADD COLUMN `name` varchar(70) NOT NULL;
ALTER TABLE `worksheet_custom_userfield` ADD COLUMN `width` int(10) unsigned NOT NULL DEFAULT 10;
ALTER TABLE `worksheet_custom_userfield` ADD COLUMN `field_id` int(10) unsigned NOT NULL auto_increment;
