name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string (e.g. 1.0.0)'
        required: true
        type: string
        default: '1.0.0'
      blis_branch:
        description: 'Branch for C4G/BLIS'
        required: true
        default: 'main'
        type: string
      blisruntime_branch:
        description: 'Branch for C4G/BLISRuntime'
        required: true
        default: 'main'
        type: string
      blisng_branch:
        description: 'Branch for C4G/BLIS-NG'
        required: true
        default: 'main'
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout BLIS
        uses: actions/checkout@v4
        with:
          repository: 'C4G/BLIS'
          ref: ${{ inputs.blis_branch }}
          path: 'BLIS'
          
      - name: Checkout BLISRuntime
        uses: actions/checkout@v4
        with:
          repository: 'C4G/BLISRuntime'
          ref: ${{ inputs.blisruntime_branch }}
          path: 'BLISRuntime'
          
      - name: Checkout BLIS-NG
        uses: actions/checkout@v4
        with:
          repository: 'C4G/BLIS-NG'
          ref: ${{ inputs.blisng_branch }}
          path: 'BLIS-NG'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: 'BLIS-NG/packages.lock.json'
          
      - name: Inject Version into HttpdConf
        working-directory: ./BLIS-NG
        run: |
          $file = "Config/HttpdConf.cs"
          $content = Get-Content $file
          $content = $content -replace 'DOCROOT = Path.Combine\(BASE_DIR, "htdocs"\);', 'DOCROOT = Path.Combine(BASE_DIR, "releases", "${{ inputs.version }}", "htdocs");'
          Set-Content $file $content

      - name: Adjust PHP Constants
        working-directory: ./BLIS
        run: |
          $file = "htdocs/includes/db_constants.php"
          $content = Get-Content $file
          $content = $content -replace '\$LOCAL_PATH = realpath\(__DIR__\."/../../local/"\);', '$LOCAL_PATH = realpath(__DIR__."/../../../../local/");'
          Set-Content $file $content

      - name: Build BLIS-NG
        working-directory: ./BLIS-NG
        run: dotnet publish -r win-x64 -c Release

      - name: Prepare Artifact Folders
        run: |
          $ver = "${{ inputs.version }}"
          mkdir BLIS-Standalone
          mkdir "BLIS-Standalone/releases/$ver"
          
          # Copy Database and Server Binaries
          Copy-Item "./BLISRuntime/dbdir" -Destination "./BLIS-Standalone/" -Recurse
          Copy-Item "./BLISRuntime/server" -Destination "./BLIS-Standalone/" -Recurse
          
          # Copy Application to Versioned Release Folder
          Copy-Item "./BLIS/htdocs" -Destination "./BLIS-Standalone/releases/$ver/" -Recurse
          Copy-Item "./BLIS/db" -Destination "./BLIS-Standalone/releases/$ver/" -Recurse
          Copy-Item "./BLIS/local" -Destination "./BLIS-Standalone/" -Recurse
          Copy-Item "./BLIS/vendor" -Destination "./BLIS-Standalone/releases/$ver/" -Recurse
          
          # Copy BLIS-NG executable
          Copy-Item "./BLIS-NG/bin/Release/net10.0/win-x64/publish/BLIS-NG.exe" -Destination "./BLIS-Standalone/"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BLIS-Standalone
          path: BLIS-Standalone/
