name: Delete Old Containers

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old blis-devcontainer builds
      uses: actions/delete-package-versions@v5.0.0
      with:   
        package-name: 'blis-devcontainer'    
        package-type: 'container'
        min-versions-to-keep: 10
        delete-only-untagged-versions: 'false'
    - name: Delete old blis builds
      uses: actions/delete-package-versions@v5.0.0
      with:   
        package-name: 'blis'    
        package-type: 'container'
        min-versions-to-keep: 50
        delete-only-untagged-versions: 'false'
