name: Build Devcontainer Docker Image (ARM64)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 2"
    
jobs:
  build:
    runs-on: ["self-hosted", "ARM64"]
    steps:
      - id: repoName
        run: echo "lowerCase=${REPO_NAME,,}" >> "$GITHUB_OUTPUT"
        env:
          REPO_NAME: ${{ github.repository }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{steps.repoName.outputs.lowerCase}}-devcontainer
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          platforms: linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
